version: "3.8"
services:
  nodejs_project:
    image: jgcapworh92/is373nextjs:main
    pull_policy: always
    ports:
      - 8080:3000
    volumes:
      - .:/app
    labels:
      com.centurylinklabs.watchtower.enable: true
